name: Rust

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Clippy (stable)
      run: |
        cargo clippy --all-targets
        cargo clippy --no-default-features
        cargo clippy --no-default-features --features="alloc"
        cargo clippy

    - name: Build (stable)
      run: |
        cargo build --verbose
        cargo build --verbose --no-default-features
        cargo build --verbose --no-default-features --features="alloc"

    - name: Run tests (stable)
      run: |
        cargo test --no-fail-fast
        cargo test --examples --no-fail-fast

    - name: Install nightly + Miri
      run: |
        rustup toolchain install nightly --component miri,clippy
        rustup override set nightly
        cargo miri setup

    - name: Clippy (nightly)
      run: |
        cargo clippy --all-targets --features="nightly"
        cargo clippy --no-default-features --features="nightly"
        cargo clippy --no-default-features --features="nightly,alloc"
        cargo clippy --features="nightly"

    - name: Build (nightly)
      run: |
        cargo build --verbose --features="nightly"
        cargo build --verbose --no-default-features --features="nightly"
        cargo build --verbose --no-default-features --features="nightly,alloc"

    - name: Run tests (nightly)
      run: |
        cargo test --features="nightly" --no-fail-fast
        cargo test --examples --features="nightly" --no-fail-fast

    - name: Run tests (nightly, miri)
      run: |
        cargo miri test --features="nightly" --no-fail-fast
        cargo miri test --examples --features="nightly" --no-fail-fast
